version: 2
jobs:
  build:
    working_directory: ~/devel

    docker:
      - image: circleci/node:10
      - image: circleci/redis:5

    steps:
      - run:
          name: Update System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get upgrade -y

      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run Tests
          command: npm run coverage

      - store_artifacts:
          path: coverage
          prefix: coverage
